FROM node:20

ENV NODE_ENV=production
ENV APP_ROOT=/app

WORKDIR ${APP_ROOT}
ADD . ${APP_ROOT}
COPY package.json ${APP_ROOT}

ARG PORT

ARG DB_HOST
ARG DB_PORT
ARG DB_USER
ARG DB_PASSWORD
ARG DB_DATABASE

ARG POSTGRES_PASSWORD
ARG POSTGRES_USER
ARG POSTGRES_DB
ARG POSTGRES_HOST
ARG POSTGRES_PORT

ENV PORT=${PORT}

ENV DB_HOST=${DB_HOST}
ENV DB_PORT=${DB_PORT}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_DATABASE=${DB_DATABASE}

ENV POSTGRES_PASSWORD=${DB_PASSWORD}
ENV POSTGRES_USER=${DB_USER}
ENV POSTGRES_DB=${DB_DATABASE}
ENV POSTGRES_HOST=${DB_HOST}
ENV POSTGRES_PORT=${DB_PORT}

EXPOSE ${PORT}
RUN yarn
RUN yarn build

CMD ["yarn", "start"]
