version: '3'

services:
  # PostgreSQL service
  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Map the database's port to the host machine
    env_file:
      - .env
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql