version: '3'

services:
  # PostgreSQL service
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "5432:5432"  # Map the database's port to the host machine
    env_file:
      - .env
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    command: "psql -U \"$POSTGRES_USER\" -d \"$POSTGRES_PASSWORD\" -a -f /docker-entrypoint-initdb.d/initdb.sql"