version: '3'

services:
  # Node.js app service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map the app's port to the host machine
    env_file:
      - .env
    depends_on:
      - db

  # PostgreSQL service
  db:
    image: postgres:latest
    ports:
      - "5432:5432"  # Map the database's port to the host machine
    env_file:
      - .env
